In [36]:
import pandas as pd
from sqlalchemy import create_engine

In [37]:
#Source: https://www.kaggle.com/datasnaek/youtube-new

In [38]:
US_data = "USvideos.csv"
UK_data = "GBvideos.csv"
CA_data = "CAvideos.csv"

In [39]:
us_videos = pd.read_csv(US_data)
uk_videos = pd.read_csv(UK_data)
ca_videos = pd.read_csv(CA_data)

In [40]:
print(us_videos.shape)
print(uk_videos.shape)
print(ca_videos.shape)
#Possible columns that we don't need:
#trending_date
#publish_time
#comments_disabled
#ratings_disabled
#video_error_or_removed
#thumbnail_link


#Goal with this project:
    #To see how trending videos may overlap with different countries, join these datasets to form a list of videos
    #that are trending in all countries selected, and hopefully be able to group them by category, type,
    #likes, view count, and anything else that could help a company/content creator decide how to reach a 
    #global audience

(40949, 16)
(38916, 16)
(40881, 16)

In [41]:
us_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...

In [42]:
dropped_us = us_videos.drop(['trending_date','comments_disabled',
                             'ratings_disabled','video_error_or_removed', 'thumbnail_link'], axis = 1)
dropped_uk = uk_videos.drop(['trending_date','comments_disabled',
                             'ratings_disabled','video_error_or_removed', 'thumbnail_link'], axis = 1)
dropped_ca = ca_videos.drop(['trending_date','comments_disabled',
                             'ratings_disabled','video_error_or_removed', 'thumbnail_link'], axis = 1)

In [43]:
dropped_us.head()

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,description
0,2kyS6SvSYSE,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,"One year after the presidential election, John..."
2,5qpjK5DgCt4,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,I know it's been a while since we did this sho...

In [44]:
#possible ways to join data:
#? Maybe get a list of categories and match it to id
#  Possible match video_id common in all three tables, get a combined csv file that has all videos
#  Get a list of category numbers, and get translation from category_id to category name
#  If we combine the data, we may need to use sqlite or nosql because the data would be relational
#  group by category, maybe group by channel,

In [45]:
category_list = open("categories.txt", "r").read()
category_list = category_list.split('\n')
category_translation = {}
for category in category_list:
    number = category.split(" ")[0]
    name = ''.join(category.split(" ")[1:])
    category_translation[int(number)] = name

In [46]:
category_translation

{1: 'Film&Animation',
 2: 'Autos&Vehicles',
 10: 'Music',
 15: 'Pets&Animals',
 17: 'Sports',
 18: 'ShortMovies',
 19: 'Travel&Events',
 20: 'Gaming',
 21: 'Videoblogging',
 22: 'People&Blogs',
 23: 'Comedy',
 24: 'Entertainment',
 25: 'News&Politics',
 26: 'Howto&Style',
 27: 'Education',
 28: 'Science&Technology',
 29: 'Nonprofits&Activism',
 30: 'Movies',
 31: 'Anime/Animation',
 32: 'Action/Adventure',
 33: 'Classics',
 34: 'Comedy',
 35: 'Documentary',
 36: 'Drama',
 37: 'Family',
 38: 'Foreign',
 39: 'Horror',
 40: 'Sci-Fi/Fantasy',
 41: 'Thriller',
 42: 'Shorts',
 43: 'Shows',
 44: 'Trailers'}

In [47]:
dropped_us = dropped_us.replace({'category_id': category_translation })
dropped_uk = dropped_uk.replace({'category_id': category_translation })
dropped_ca = dropped_ca.replace({'category_id': category_translation })

In [48]:
dropped_us

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,description
0,2kyS6SvSYSE,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,People&Blogs,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,Entertainment,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,"One year after the presidential election, John..."
2,5qpjK5DgCt4,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,Comedy,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,Entertainment,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,I Dare You: GOING BALD!?,nigahiga,Entertainment,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,I know it's been a while since we did this sho...
...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,The Cat Who Caught the Laser,AaronsAnimals,Pets&Animals,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,True Facts : Ant Mutualism,zefrank1,People&Blogs,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,NaN
40946,D6Oy4LfoqsU,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,Entertainment,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,How Black Panther Should Have Ended,How It Should Have Ended,Film&Animation,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,How Black Panther Should Have EndedWatch More ...
40948,ooyjaVdt-jA,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,Gaming,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,Call of Duty: Black Ops 4 Multiplayer raises t...

In [49]:
combined_videos = pd.merge(dropped_us, dropped_uk, how = 'inner', on = 'title')
combined_videos = pd.merge(combined_videos, dropped_ca, how = 'inner', on = 'title')
combined_videos.columns
#print(combined_videos["title"].nunique())
#combined_videos.columns
combined_videos = combined_videos[['channel_title_x', 'category_id_x', 'tags_x']]
combined_videos = combined_videos.drop_duplicates()
combined_videos = combined_videos.reset_index(drop = True)

In [50]:
combined_videos

,channel_title_x,category_id_x,tags_x
0,BostonDynamics,Science&Technology,"Robots|""Boston Dynamics""|""SpotMini""|""Legged Lo..."
1,EminemVEVO,Music,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In..."
2,JenniferLopezVEVO,Music,"Jennifer Lopez ft. Wisin|""Jennifer Lopez ft. W..."
3,Ed Sheeran,Music,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove..."
4,The Tonight Show Starring Jimmy Fallon,Comedy,"Jimmy Fallon|""Tonight Show Starring Jimmy Fall..."
...,...,...,...
503,Universal Pictures,Entertainment,"halloween|""horror""|""horror movie""|""scary movie..."
504,Maroon5VEVO,Music,"Maroon 5|""Adam Levine""|""3 Little Birds""|""Girls..."
505,Jimmy Kimmel Live,Entertainment,"jimmy|""kimmel""|""live""|""late""|""night""|""talk""|""s..."
506,Disney Movie Trailers,Film&Animation,"Disney|""Walt Disney Studios""|""Dumbo""|""Flying E..."
507,America's Got Talent,Entertainment,"America's Got Talent 2018|""america's got talen..."

In [51]:
top_500 = "top_500.csv"

In [52]:
top_500_df = pd.read_csv(top_500)
top_500_df

,Rank,Grade,Ch_name,Uploads,Subscriptions,Views
0,1st,A++,T-Series,"14,297",135M,"104,724,369,854"
1,2nd,A++,Cocomelon - Nursery Rhymes,517,78.2M,"57,054,290,512"
2,3rd,A++,✿ Kids Diana Show,691,50.9M,"24,157,678,368"
3,4th,A++,Like Nastya,400,52.2M,"30,591,257,306"
4,5th,A++,SET India,"37,017",69.3M,"52,149,505,781"
...,...,...,...,...,...,...
495,496th,A,FutureVEVO,227,4.56M,"4,042,110,575"
496,497th,A,Coca-Cola,"3,490",3.41M,"2,837,595,239"
497,498th,A,Great Indian Comedy,561,5.77M,"1,236,648,117"
498,499th,A,Doggy Doggy Cartoons,"2,742",16.4M,"5,940,758,926"
499,500th,A,FunFun Toy Doll TV,690,11M,"4,415,663,688"

In [53]:
combined_channels = pd.merge(top_500_df, combined_videos, how = 'inner', left_on = 'Ch_name', right_on = 'channel_title_x')

In [54]:
combined_channels = combined_channels[['Rank','Grade','Ch_name','Uploads','Subscriptions','Views','category_id_x']]
combined_channels = combined_channels.drop_duplicates()
combined_channels = combined_channels.reset_index(drop = True)

In [55]:
combined_channels_dict  = combined_channels.to_dict()
channel_ranks = combined_channels_dict["Rank"]
for index, rank in channel_ranks.items():
    rank_integer = int(rank.strip()[:-2])
    combined_channels_dict["Rank"][index] = rank_integer

In [56]:
channel_ranks

{0: 19,
 1: 67,
 2: 95,
 3: 121,
 4: 166,
 5: 167,
 6: 178,
 7: 210,
 8: 250,
 9: 261,
 10: 298,
 11: 305,
 12: 326,
 13: 326,
 14: 329,
 15: 347,
 16: 359,
 17: 362,
 18: 363,
 19: 364,
 20: 368,
 21: 406,
 22: 431,
 23: 432,
 24: 454,
 25: 469}

In [57]:
Channel_Ranks = pd.DataFrame.from_dict(combined_channels_dict)
Channel_Ranks = Channel_Ranks.sort_values(by='Rank', ascending = True)
Channel_Ranks.rename(columns = {'Ch_name':'Channel','category_id_x':'Category'}, inplace = True)
Channel_Ranks

,Rank,Grade,Channel,Uploads,Subscriptions,Views,Category
0,19,A+,WWE,"47,028",57.4M,"41,299,497,565",Sports
1,67,A,MBCentertainment,"74,049",6.86M,"9,251,564,684",Entertainment
2,95,A,TheEllenShow,"11,663",37.2M,"19,484,559,580",Entertainment
3,121,A,Saturday Night Live,"7,247",10M,"8,936,403,581",Entertainment
4,166,A,Inside Edition,"19,513",7.33M,"10,868,638,100",News&Politics
5,167,A,jypentertainment,"1,089",15.2M,"8,489,732,766",Music
6,178,A,SMTOWN,"3,516",21.9M,"16,064,678,295",Music
7,210,A,Ed Sheeran,161,44.1M,"19,663,862,347",Music
8,250,A,jbalvinVEVO,172,13.6M,"13,682,100,750",Music
9,261,A,Mnet K-POP,"18,912",13.3M,"8,357,545,782",Entertainment
10,298,A,shakiraVEVO,165,18.9M,"17,620,883,202",Music
11,305,A,NBA,"33,422",13.8M,"6,797,433,345",Sports
13,326,A,Jimmy Kimmel Live,"4,652",16.5M,"9,675,184,935",Entertainment
12,326,A,Jimmy Kimmel Live,"4,652",16.5M,"9,675,184,935",Comedy
14,329,A,Marshmello,421,44.4M,"8,560,476,910",Music
15,347,A,LadyGagaVEVO,146,9.21M,"8,417,160,963",Music
16,359,A,TheWeekndVEVO,74,10.9M,"8,936,073,854",Music
17,362,A,Maroon5VEVO,121,15.1M,"14,901,418,348",Music
18,363,A,David Dobrik,626,16.7M,"7,109,918,732",People&Blogs
19,364,A,KatyPerryVEVO,140,25.6M,"19,001,952,411",Music
20,368,A,CNN,"147,973",9.24M,"6,421,938,011",News&Politics
21,406,A,Dua Lipa,116,13.1M,"4,524,668,497",Music
22,431,A,EminemVEVO,86,25.7M,"14,571,153,913",Music
23,432,A,TaylorSwiftVEVO,118,26.9M,"18,520,025,111",Music
24,454,A,Markiplier,"4,647",25.4M,"12,829,871,171",Comedy
25,469,A,Atlantic Records,"1,072",10.6M,"9,004,447,459",Music

In [58]:
rds_connection_string = "postgres:postgres@database-anh.c6zobidrus2h.us-east-2.rds.amazonaws.com:5432/youtube_video"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [59]:
engine.table_names()

[]

In [ ]:
new_customer_data_df.to_sql(name='customer_name', con=engine, if_exists='append', index=False)